### ISSUE TITLE
How use it in Flask/Django app?

### ISSUE THREAD

**Issue by Draqun** [benalexkeen/C3PyO#11]
There are some examples which show how use it in Django/Flask app in templates?

**Comment by benalexkeen** [comment]
Just merged in a PR with a Flask example ([see here](https://github.com/benalexkeen/C3PyO/tree/master/examples/flask)). I'll have to add this to the documentation but, in short, the steps are:
- call chart method `chart.bind_to('your_div_id_here')` to make sure this chart binds to a particular div id in your template.
- call chart method `chart.json()` to get the json that can be passed to your templates.
- Include the css from C3, and the javascript files from C3 and D3 in your template
- Add the following code to your template body:
```html
<div id='line_chart_div'></div>
<script type="text/javascript">
    c3.generate({{chart_json|safe}})
</script>
```

**Comment by Draqun** [comment]
Thank you very much :)
